apiVersion: v1
kind: PersistentVolume
metadata:
  name: brewery-data-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/brewery-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brewery-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi